### ISSUE TITLE
Measuring the time-duration

### ISSUE THREAD

**Issue by bhavishyagopesh** [hackcave/pynctual#21]
Probably a program that ,at the end of the day, runs through the (second db, ref-> #20 ) and measures the time-duration and finally reports "total_work_duration".

**Comment by dhruvkmr96** [comment]
I am working on it.

**Comment by dhruvkmr96** [comment]
Done.

**Comment by adarshaj** [comment]
@dhruvkmr96 ?? you have to send pull request

**Comment by bhavishyagopesh** [comment]
closed as irrelevant now
