### ISSUE TITLE
Making an API call to ryver(and donbot) to report exceptions if any.

### ISSUE THREAD

**Issue by bhavishyagopesh** [hackcave/pynctual#22]
IF `total_work_duration`(#21) turns out to be below some number, Make an [API call](http://support.ryver.com/ryver-apis-overview/) to ryver hence posting the exception on channel.

**Comment by samarth9** [comment]
Is anyone doing anything about this? If not, I will work on it.

**Comment by bhavishyagopesh** [comment]
closed by #25
